kind: Service
apiVersion: v1
metadata:
  namespace: train-schedule
  name: train-schedule-service
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: train-schedule
    name: train-schedule    
spec:
  type: NodePort
  selector:
    app: train-schedule
    name: train-schedule
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 8081
  externalIPs:
  - 3.101.116.70
  - 50.18.246.179
    
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: train-schedule
  name: train-schedule-deployment
  labels:
    app: train-schedule
    name: train-schedule    
spec:
  replicas: 2
  selector:
     matchLabels:
       app: train-schedule
       name: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
        name: train-schedule
    spec:
      containers:
      - name: train-schedule-container
        image: ldfoskey007/train-schedule:latest
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: train-schedule
  namespace: train-schedule
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: train-schedule-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
